version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: nest-mongo
    ports:
      - "19020:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}