version: '3'
services:
  database:
    image: mongo
    container_name: nest-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - '19020:27017'
  backend:
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/learn/nest/.env
    depends_on:
      - database
    build:
      context: /learn/nest/
      dockerfile: ./Dockerfile
